const Data = [
    {
        id: 1,
        category: "education",
        icon: "icon-graduation",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
    {
        id: 2,
        category: "education",
        icon: "icon-graduation",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
    {
        id: 3,
        category: "education",
        icon: "icon-graduation",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
    {
        id: 4,
        category: "experience",
        icon: "icon-briefcase",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
    {
        id: 5,
        category: "experience",
        icon: "icon-briefcase",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
    {
        id: 6,
        category: "experience",
        icon: "icon-briefcase",
        year: "2019 - 2021",
        title: "Master of Science in Computer Science",
        institution: "University of California, Los Angeles",
        desc: "asd",
    },
];

export default Data